import type { Scene } from "../engine/types";
import { aside, say, voice, choice, visit, image } from "./voice";

export const modernScene: Scene = {
  id: "modern", title: "STATION 7", subtitle: "DAY 9,999 · 2:15 PM", atmosphere: "modern",
  room: image("modern-room"), character: "absent", tableau: true,
  intro: [
    aside("Elsewhere in the building, the same arrangement: a desk, three cabinets, shelves at the right."),
    aside("No coffee rings. No loose screws. A fan makes a sound without syllables.", { duration: 4000 }),
    aside("One small light changes. A technician comes in carrying a sealed box.", { cue: "operator-enter" }),
    { speaker: "TECHNICIAN", text: "Slot six. Revision D. Good." },
    aside("He draws out a module, slots in another, and scans the label on the box.", { sound: "clack", cue: "operator-work" }),
    { speaker: "PHONE", text: "You're on the last legacy room Monday, aren't you?" },
    { speaker: "TECHNICIAN", text: "Four. Assessment first, then isolate and label." },
    { speaker: "PHONE", text: "The gentleman there finishes Friday. He's left notes." },
    { speaker: "TECHNICIAN", text: "Good. I'll leave those with the archive copy." },
    aside("He puts the old module in the box the new one came in. There is a prepaid label on the lid."),
    aside("The light returns to white. He leaves. The fan is unchanged.", { duration: 5000, cue: "operator-leave" }),
  ], hotspots: [], outro: [],
  ending: { title: "", text: "", nextLabel: "Friday · Day 10,000" },
};

export const finalScene: Scene = {
  id: "retirement", title: "STATION 4", subtitle: "DAY 10,000 · 3:42 PM", roundTitle: "ONE LAST ROUND", retirement: true,
  intro: [
    aside("A small cake. Three paper cups. The good coffee, in a flask from home."),
    say("They had sandwiches upstairs. I brought you the quiet bit."),
    aside("The auction listing has ended. The last seller's reply is short: already stripped, sorry."),
    say("All right. I thought that might be it."),
    aside("He closes the browser. For once, he does not leave the search running."),
  ],
  hotspots: [
    visit("desk", "Retirement tea", [
      aside("The envelope from upstairs says ten thousand days of service. He has put it beneath the flask so it won't curl."),
      say("I used to think the last day would feel—", { choices: [
        choice("—different.", "last_day", "different",
          say("I'd wake up knowing something. It was just the alarm."),
          aside("He pours coffee into a paper cup and sets it beside the chipped mug."),
          say("Tomorrow I can leave it ringing. I might not.")),
        choice("—finished.", "last_day", "finished",
          say("An empty page. All the little jobs crossed out."),
          aside("A shopping list shows through the back of the final log sheet."),
          say("I've still got to buy milk.")),
        choice("—like any other Friday.", "last_day", "ordinary",
          say("And mostly it does. The clock's in the same place."),
          aside("He straightens the cups, then moves one back out of line."),
          say("Except I wouldn't normally buy a whole cake.")),
      ] }),
      say("One for each of you. I'll have the mug."),
      aside("He cuts four pieces. No one is hurried to eat."),
    ]),
    visit("jerry", "Jerry", [
      voice("jerry"),
      aside("Behind the transport, a timing contact of the same old pattern. It has worked less often than Mike's."),
      say("I can't get another. Yours would fit."),
      say("Ellis would have called this—", { choices: [
        choice("—a sensible repair.", "sacrifice", "sensible",
          say("He hated leaving a good part unused."),
          aside("The technician measures the mounting holes anyway. They are exactly right."),
          say("He'd have checked twice too.")),
        choice("—robbing Peter.", "sacrifice", "borrowing",
          say("He never mentioned when Peter got it back."),
          aside("He rests the screwdriver on the unopened cover."),
          say("Sorry, Jerry. I don't think this is a loan.")),
        choice("—making do.", "sacrifice", "making do",
          say("As if there weren't years inside those two words."),
          aside("He runs a thumb over the smooth place where the latch has been opened a thousand times."),
          say("You've done quite enough of it.")),
      ] }),
      say("Not yet. Finish what you're saying."), voice("jerry"),
    ]),
    visit("mike", "Mike", [
      voice("mike"), aside("The contact closes, but softly. He can feel the little hesitation even with the door shut."),
      say("I thought I'd have seen it by now.", { recollection: { key: "green_circle", versions: {
        "a promised result": "Ten thousand days. I thought I'd have seen Ellis's green circle by now.",
        "an end to the question": "Ten thousand days. Still painting around that question mark.",
        "perfect harmony": "Ten thousand days. Still trying to leave exactly enough room for the next note.",
      } } }),
      say("Perhaps I was listening for—", { choices: [
        choice("—their approval.", "masters", "approval",
          say("A green light from men who'd already gone home."),
          aside("His reflection darkens the circular window. He moves his head aside."),
          say("Ellis would have told me to go home too.")),
        choice("—what they heard.", "masters", "their music",
          say("Before there was a cabinet. Before the drawings."),
          aside("The pencil marks follow the circuit across three pages. It could almost be a score."),
          say("I think I've heard pieces of it.")),
        choice("—something of my own.", "masters", "his own work",
          say("Their machines. My adjustments. Hard to say where one ends."),
          aside("A replacement bracket bears his initials, nearly lost beneath the old maker's plate."),
          say("That's all right. Doesn't need sorting out.")),
      ] }),
      say("I'll set the delay for the room after it cools. That's when you nearly agree."),
      aside("He writes the new setting beneath the old one. No line is crossed out."),
    ]),
    visit("linda", "Linda", [
      voice("linda"), say("You've been very patient."),
      say("What I'll miss is—", { choices: [
        choice("—knowing the weather.", "goodbye", "weather",
          say("Without a window. Without opening my phone."),
          aside("He puts his palm against the cool return pipe."),
          say("I'll have windows at home. It'll feel like cheating.")),
        choice("—having someone to talk to.", "goodbye", "company",
          say("Someone who doesn't mind hearing the same thing twice."),
          aside("The pressure valve breathes while he searches for another sentence."),
          say("Well. You heard most of it already.")),
        choice("—knowing where to put my hands.", "goodbye", "hands",
          say("Before I've even decided what to do."),
          aside("He closes the latch without looking. His fingers know when it has caught."),
          say("I'll have to find them something else.")),
      ] }),
      say("The others need you tonight. After that, you can rest."),
    ]),
    visit("parts", "Old work", [
      aside("The heap has been sorted into KEEP, ARCHIVE, and two boxes without labels."),
      say("I'm taking—", { choices: [
        choice("—the notebook.", "keepsake", "notebook",
          say("They've got a copy. All the useful pages."),
          aside("He opens a page that contains only a date and six little circles."),
          say("I kept some for myself.")),
        choice("—Ellis's wooden spacer.", "keepsake", "spacer",
          say("It fits in my pocket. That helps."),
          aside("The spacer is polished on one side and rough on the other."),
          say("I could varnish it. I won't.")),
        choice("—the chipped mug.", "keepsake", "mug",
          say("Nobody else wants it. Nobody wanted it when it was new."),
          aside("He wraps it in a clean work cloth, handle uppermost."),
          say("Still. It knows how I take it.")),
      ] }),
      aside("On the boxes he writes dates, part numbers, the names of people to ask. Then he draws a line through Ellis's phone number."),
      say("Sorry. Should have done that years ago."),
    ]),
  ],
  outro: [
    say("Right. One last job."),
    aside("He lets the tape bank finish its cycle. Isolates its supply. The reels stop.", { cue: "sacrifice", sound: "click" }),
    aside("The contact comes out of Jerry and goes into Mike. Four screws, two leads. He sets the delay for the cooler room.", { sound: "clank" }),
    voice("mike"), voice("linda"),
    aside("Jerry's dark window leaves a space between the other two."),
    say("There. Keep one another company."),
    say("And thank you. All of you."),
    aside("He closes the notebook, switches off the desk lamp, and takes his coat.", { cue: "leave" }),
    aside("The door catches. His hand comes back once to pull it properly shut.", { sound: "click", duration: 4000 }),
  ],
  ending: { title: "", text: "", nextLabel: "4:00 AM" },
};

export const nightScene: Scene = {
  id: "four-am", title: "STATION 4", subtitle: "4:00 AM", character: "absent", atmosphere: "harmony", tableau: true,
  intro: [
    aside("", { cue: "harmony", duration: 16000 }),
  ], hotspots: [], outro: [],
  ending: { title: "", text: "", nextLabel: "Monday morning" },
};

export const morningScene: Scene = {
  id: "day-one", title: "STATION 4", subtitle: "DAY 1 · 8:00 AM", character: "absent", atmosphere: "harmony", tableau: true,
  intro: [
    aside("A new coat on the same screw. A tablet on the desk, beside the envelope.", { cue: "operator-enter" }),
    { speaker: "NEW TECHNICIAN", text: "Three cabinets. One already isolated." },
    aside("He photographs the serial plates and checks each supply against his list. The small green circle is behind his shoulder."),
    { speaker: "NEW TECHNICIAN", text: "Notes are here. I'll box those separately." },
    aside("He opens the isolator. The sound stops.", { cue: "shutdown", sound: "click", duration: 5000 }),
    aside("", { duration: 4000 }),
  ], hotspots: [], outro: [],
  ending: { title: "STATION 4", text: "", nextLabel: "" },
};
