import type { Scene } from "../engine/types";
import { aside, say, voice, choice, visit } from "./voice";

export const sceneOne: Scene = {
  id: "midday", title: "STATION 4", subtitle: "DAY 9,997 · 1:47 PM", roundTitle: "MIDDAY ROUND",
  ending: { title: "DAY 9,997", text: "Six seconds nearer.", nextLabel: "Begin day 9,998" },
  intro: [
    aside("The coffee has gone cold. A parts listing refreshes without changing."),
    aside("Behind the desk, three machines keep slightly different time."),
    say("No. That last one was new."),
  ],
  hotspots: [
    visit("desk", "Parts terminal", [
      aside("Three listings since lunch. Two are mislabeled. The third is a printer supply photographed from a hopeful angle.", { sound: "click" }),
      say("The number is on the casing. The casing hasn't belonged to that part since 1986."),
      say("Mostly I learned to search for—", { choices: [
        choice("—what the old men called it.", "search_language", "the inherited name",
          say("Ellis called this one a swallow. Nobody else did."),
          aside("He types SWALLOW RELAY into the search box. Birds, jewelry, one dismantled telephone exchange."),
          say("Telephone people knew him, apparently.")),
        choice("—the noise it makes when it fails.", "search_language", "the failing sound",
          say("Not the sound itself. What somebody would complain about."),
          aside("He searches CHATTERING CONTACT. A seller has uploaded a short, shaky video."),
          say("That's the one. He thinks it's supposed to do that.")),
        choice("—the machine it used to belong to.", "search_language", "the missing machine",
          say("A switchboard, sometimes. A lift controller, once."),
          aside("He opens a photograph of an empty mounting plate. The spacing of the screw holes is familiar."),
          say("There. You can tell by what isn't there.")),
      ] }),
      aside("Six untested timing relays at a county auction. Shipping costs more than the box."),
      say("I'll ask whether he'll sell just one."),
      aside("He saves the listing beside eleven others. The notebook has room for one more number.", { sound: "click" }),
    ]),
    visit("jerry", "Tape bank", [
      voice("jerry"), say("Easy, Jerry. I heard you the first time."),
      aside("A gate catches, the capstan rasps, then a high index tone. Almost a name. After enough afternoons, a name."),
      say("Ellis said you learned these—", { choices: [
        choice("—by sound.", "first_lesson", "by sound",
          say("He put the meter down and made me close my eyes."),
          aside("The technician closes his eyes. The rasp comes from the left guide, not the motor."),
          say("He let me be wrong twice. Then he moved my hand.")),
        choice("—by touch.", "first_lesson", "by touch",
          say("Back of the fingers. Not your palm. You'll hold on too long."),
          aside("Two fingers rest against the casing. A small vibration arrives before each turn."),
          say("He had a scar exactly there. Never said from what.")),
        choice("—by letting them finish.", "first_lesson", "by waiting",
          say("I used to interrupt. Open the door before the third sound."),
          aside("He lets the sequence repeat. The final tone is steady; only the first two are hurrying."),
          say("He said I did it to people too.")),
      ] }),
      aside("A quarter turn on the tension screw. The rough middle softens.", { sound: "clack" }),
      voice("jerry"), say("Better. Not younger. Better."),
    ]),
    visit("mike", "Timing core", [
      voice("mike"), aside("A low transformer hum, an oscillator climbing, a dry contact at the end. Mike."),
      say("Three milliseconds out. You used to do better than that."),
      aside("Two indicator windows: a square and a circle. Both dark. Their glass is polished more carefully than the surrounding panel."),
      say("Ellis said when they all agreed, the circle would—", { choices: [
        choice("—turn green.", "green_circle", "a promised result",
          say("He'd seen it once. Or said he'd seen it once."),
          aside("A page in the notebook lists dates, then a column of empty circles."),
          say("I started that page my first winter. Had to bind in another.")),
        choice("—stop asking.", "green_circle", "an end to the question",
          say("Not an alarm. More like a sentence left open."),
          aside("Under the meter somebody has penciled a tiny question mark. It has survived three coats of paint."),
          say("I didn't put that there. I just kept painting around it.")),
        choice("—sound like nothing was wrong.", "green_circle", "perfect harmony",
          say("The gap between each one exactly big enough for the next."),
          aside("He taps three unequal intervals on the casing, then tries them again."),
          say("They drew it as a circuit. I think they heard it first.")),
      ] }),
      say("Nearly ten thousand days. I've got very good at nearly."),
      aside("He adjusts the oscillator a fraction. The circle stays dark."), say("Closer."),
    ]),
    visit("linda", "Cooling stack", [
      voice("linda"), say("Linda."),
      aside("The intake whistles, the fan holds a nasal drone, the valve lets out a soft breath. She is the only one whose sentence ends gently."),
      say("She always ran—", { choices: [
        choice("—hot when it rained.", "linda_past", "weather-sensitive",
          say("Before the gutters started. Before I remembered my coat."),
          aside("He checks the pipe with the back of his hand, then glances toward the ceiling."),
          say("Clear today. Probably clear tomorrow.")),
        choice("—quiet when people visited.", "linda_past", "shy around visitors",
          say("Ellis thought I imagined it. Then an inspector came."),
          aside("He steps back from the grille. The fan does not change its mind."),
          say("Just me, Linda. You can carry on.")),
        choice("—steadier than the others.", "linda_past", "the reliable one",
          say("Jerry complained. Mike lost count. She kept the room comfortable."),
          aside("The pressure needle trembles over the same narrow patch of worn paint."),
          say("Always left her till last. That wasn't fair, really.")),
      ] }),
      aside("He bleeds a little air from the line. The needle settles.", { sound: "steam" }),
      say("Thank you."),
    ]),
    visit("parts", "Parts heap", [
      aside("A relay wrapped in a work order from 1989. The contact is black. The paper is almost transparent.", { sound: "clank" }),
      say("I used to think this pile was—", { choices: [
        choice("—what they left me.", "parts_pile", "an inheritance",
          say("Ellis showed me the good shelf. Then said all the shelves were good."),
          aside("He finds a little wooden spacer, shaped by hand to fit one particular door."),
          say("He made that because it rattled during lunch.")),
        choice("—what they couldn't solve.", "parts_pile", "unfinished work",
          say("That seemed unlikely. They could solve anything."),
          aside("The work order has three crossed-out drawings and a fourth left unfinished."),
          say("Took me years to notice the crossings-out.")),
        choice("—the department's memory.", "parts_pile", "a memory",
          say("The official archive is upstairs. This one's easier to read."),
          aside("A coffee ring encloses a set of initials. Beside it: TRY AFTER LUNCH."),
          say("I remember that cup. I don't remember the repair.")),
      ] }),
      aside("The dead relay goes into his pocket. The paper goes into his notebook."),
      say("One might still be useful. The other already was."),
    ]),
  ],
  outro: [
    aside("For six seconds the gaps almost fit."),
    say("I know. I heard it too."),
    aside("No indicator changes. He writes the time in the notebook."),
    say("All right. Keep talking."),
  ],
};
