import type { Scene } from "../engine/types";
import { aside, say, voice, choice, visit } from "./voice";

export const sceneTwo: Scene = {
  id: "red-square", title: "STATION 4", subtitle: "DAY 9,998 · 8:06 AM", roundTitle: "MORNING ROUND", faultIndicator: true,
  ending: { title: "DAY 9,998", text: "The square is dark. The circle is dark too.", nextLabel: "The following afternoon" },
  intro: [
    aside("The red square has come on before the desk lamp."),
    say("Morning. Yes, I see it."),
    aside("He hangs his coat on the same screw and sets his coffee beside yesterday's cup."),
    say("Let me get settled."),
  ],
  hotspots: [
    visit("desk", "Modernization notice", [
      aside("FINAL LEGACY SYSTEM MODERNIZATION. Site assessment: Monday, 8:00. An ordinary calendar invitation.", { sound: "click" }),
      say("They remembered my last day. That's decent of them."),
      say("Modernization. I suppose it means—", { choices: [
        choice("—someone else gets a quieter room.", "modernization", "quiet",
          say("They won't have to talk over the fan on the phone."),
          aside("He turns down the terminal speaker. The fan carries on behind him."),
          say("I'll miss being able to blame it when I didn't hear.")),
        choice("—the work becomes different.", "modernization", "different work",
          say("Less solder. More passwords, probably."),
          aside("The invitation includes a training link. He bookmarks it, out of habit."),
          say("Somebody will be good at that. It won't have to be me.")),
        choice("—there's finally room to move.", "modernization", "more space",
          say("Three cabinets into half of one. They can get rid of the heap."),
          aside("He looks toward the far corner, as though measuring the floor beneath it."),
          say("I haven't seen that bit of wall since they put the pipe in.")),
      ] }),
      aside("He accepts the appointment. The message stays open beside the parts search."),
      say("The auction man hasn't answered."),
      say("I'll try a different listing.", { recollection: { key: "search_language", versions: {
        "the inherited name": "I'll try swallow again. With quotation marks this time.",
        "the failing sound": "I'll ask the man with the video to take the cover off.",
        "the missing machine": "I'll ask whether he kept anything from behind that mounting plate.",
      } } }),
    ]),
    visit("jerry", "Tape bank", [
      voice("jerry"), say("Jerry is fine. Jerry would like that recorded."),
      aside("A ribbon of oxide has gathered beneath the left guide. He folds a cloth into a clean corner."),
      say("A new system would—", { choices: [
        choice("—run quieter.", "new_system", "quieter",
          say("Useful. You can hear yourself think."),
          aside("He listens while the cloth lifts the grit. The rasp thins but does not vanish."),
          say("Of course, I've got used to thinking around this.")),
        choice("—diagnose itself.", "new_system", "self-diagnosing",
          say("Tell you which board. Tell you before it failed, maybe."),
          aside("He draws a short line beside yesterday's measurement."),
          say("I used to think that meant nobody would need to learn. It means they'd learn something else.")),
        choice("—replace this entire room.", "new_system", "room-sized replacement",
          say("And use less power than my desk lamp. Nearly."),
          aside("The cloth catches on a screw head someone replaced with a slightly larger one."),
          say("Nobody'll have to remember which screw that is.")),
      ] }),
      aside("He cleans the guide without opening the motor cover.", { sound: "clack" }),
      say("Still got yesterday's quarter turn."), voice("jerry"),
    ]),
    visit("mike", "Red square", [
      voice("mike", true),
      aside("Hum, climb, silence. The third contact doesn't close. The square reports the disagreement; the circle reports something rarer."),
      say("It isn't quite broken. It's—", { choices: [
        choice("—late.", "daily_failure", "late",
          say("Three milliseconds. The old log has thirty written in it."),
          aside("He holds the card against the scale engraved inside the door."),
          say("I'm always comparing it with its best day. Perhaps that's unfair.")),
        choice("—tired.", "daily_failure", "tired",
          say("The contact doesn't spring all the way back."),
          aside("He flexes his own fingers before loosening the retaining screw."),
          say("I know. Cold mornings.")),
        choice("—doing what it always does.", "daily_failure", "habitual",
          say("Same card. Same time. Nothing else has moved."),
          aside("The fault log opens naturally at a thumb-darkened page."),
          say("Habit is useful. Right up until it isn't.")),
      ] }),
      aside("Isolate the card. Count five. Clean the contact. Reseat it. The pencil rests beside the switch, not across it.", { sound: "clank" }),
      aside("The red square goes dark. The circular window does not light.", { cue: "repair" }),
      voice("mike"), say("There you are. That's the morning sorted."),
    ], { focusEffect: "fault-lights", clearsFault: true }),
    visit("linda", "Cooling stack", [
      voice("linda"), aside("Pressure unchanged. Intake temperature one degree lower."),
      say("Clear weather, then.", { recollection: { key: "linda_past", versions: {
        "weather-sensitive": "No rain, then. You'd have told me.",
        "shy around visitors": "Someone's coming Monday. You can be quiet for them if you like.",
        "the reliable one": "I haven't forgotten you. I'm just taking my time today.",
      } } }),
      say("Reliable means—", { choices: [
        choice("—nothing changes.", "reliable", "unchanging",
          say("That's what I used to write in the report."),
          aside("Yesterday's pencil mark is a little to the right of today's."),
          say("Now I write the number. It tells the truth better.")),
        choice("—you know how it changes.", "reliable", "familiar change",
          say("A degree with the weather. Another with the dust."),
          aside("He wipes the gauge glass rather than adjusting the needle."),
          say("Not every change needs correcting.")),
        choice("—it fails where you can reach it.", "reliable", "reachable failure",
          say("Four screws. Enough space to put your hand in."),
          aside("He tests one screw gently, then leaves it alone."),
          say("Whoever drew that cover had to take one off.")),
      ] }),
      aside("He records the temperature and closes the notebook. Linda finishes her breath."),
    ]),
    visit("parts", "Parts heap", [
      aside("The spare timing card is dated in pencil: 4/12/91. Beneath it another date has been rubbed away.", { sound: "clank" }),
      say("A new part arrives—", { choices: [
        choice("—sealed.", "modern_part", "sealed",
          say("No fingerprints inside. No question about where it's been."),
          aside("He checks the old card for a hairline crack under the desk light."),
          say("There is something to be said for that.")),
        choice("—identical.", "modern_part", "identical",
          say("You can put another in without moving the holes."),
          aside("This card has one hole filed into an oval. He recognizes his own work."),
          say("I could have used that in '91.")),
        choice("—with instructions.", "modern_part", "documented",
          say("Not a note saying ask Ellis. Actual instructions."),
          aside("The faded note on this card does, in fact, say ASK ELLIS."),
          say("I should write something underneath.")),
      ] }),
      aside("On a clean label he writes: THIRD CONTACT. CLEAN BEFORE REPLACING. He leaves it where it can be found."),
    ]),
  ],
  outro: [
    aside("The three machines resume their imperfect measure. He warms his hands around the fresh cup."),
    say("Two more mornings."),
    aside("He doesn't say it a second time."),
  ],
};
